### ISSUE TITLE
Unable to Visualize Muse Stream

### ISSUE THREAD

**Issue by kushaalrao** [alexandrebarachant/muse-lsl#138] opened 2020-10-21 20:43 UTC
I am able to connect my Muse with the BLED112 Dongle and initiate a stream. When I open a new terminal window and try to visualize the data, I am not able to do so. 
![Screen Shot 2020-10-21 at 1 42 00 PM](https://user-images.githubusercontent.com/14986642/96785297-734daf00-13a3-11eb-8e08-466e776256e6.png)

**Comment by oori** [comment] 2020-11-14 18:02
duplicate of https://github.com/alexandrebarachant/muse-lsl/issues/111

**Closed** 2021-01-10 19:43 UTC
