### ISSUE TITLE
OSX Muse 2016 NotConnectedError during connection attempt with BLED112

### ISSUE THREAD

**Issue by lguerdan** [alexandrebarachant/muse-lsl#64] opened 2018-11-03 22:22 UTC
Hi there, I am experiencing issues connecting my 2016 Muse headband to muse-LSL. When I attempt to stream with my device or find its MAC address I receive the following errors. 

muselsl stream --name Muse-660F

```
Traceback (most recent call last):
  File "/usr/local/bin/muselsl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/muselsl/__main__.py", line 51, in main
    cli = CLI(args.command)
  File "/usr/local/lib/python2.7/site-packages/muselsl/cli.py", line 9, in __init__
    getattr(self, command)()
  File "/usr/local/lib/python2.7/site-packages/muselsl/cli.py", line 42, in stream
    args.interface, args.name)
  File "/usr/local/lib/python2.7/site-packages/muselsl/stream.py", line 61, in stream
    found_muse = find_muse(name)
  File "/usr/local/lib/python2.7/site-packages/muselsl/stream.py", line 47, in find_muse
    muses = list_muses()
  File "/usr/local/lib/python2.7/site-packages/muselsl/stream.py", line 25, in list_muses
    adapter.start()
  File "/Users/lukeguerdan/School/capstone/muse-lsl/src/pygatt-fork/pygatt/backends/bgapi/bgapi.py", line 188, in start
    self._open_serial_port(max_connection_attempts=1)
  File "/Users/lukeguerdan/School/capstone/muse-lsl/src/pygatt-fork/pygatt/backends/bgapi/bgapi.py", line 171, in _open_serial_port
    "No BGAPI compatible device detected")
pygatt.exceptions.NotConnectedError: No BGAPI compatible device detected
```

python scan_devices.py
```
Traceback (most recent call last):
  File "scan_devices.py", line 17, in <module>
    list_devices = adapter.scan(timeout=10.5)
  File "/Users/lukeguerdan/School/capstone/muse-lsl/src/pygatt-fork/pygatt/backends/bgapi/bgapi.py", line 315, in scan
    scan_interval, scan_window, parameters
  File "/Users/lukeguerdan/School/capstone/muse-lsl/src/pygatt-fork/pygatt/backends/bgapi/bgapi.py", line 262, in send_command
    raise NotConnectedError()
pygatt.exceptions.NotConnectedError
```

I have connected a BLED112 dongle to my USB port as I attempt to connect. The issue seems to be related either to the connection of the underlying bgapi or some configuration on my Mac. 

- Running High Sierra 10.13.6. 
- [BLED112-V1](https://www.silabs.com/products/wireless/bluetooth/bluetooth-low-energy-modules/bled112-bluetooth-smart-dongle) manufactured by Silicon Labs 

There is a related issue for bgapi [here](https://github.com/peplin/pygatt/issues/159). I added the same timeout to pygatt's `start()` function, but this did not solve the issue. This makes me think the issue is related to device connection. When I run `system_profiler SPUSBDataType`, I do not see any dongle information (which I believe I should). Do I need to install an additional driver or configure anything on my device? 

Any suggestions or debugging tips would be greatly appreciated.

**Comment by jdpigeon** [comment] 2018-11-03 22:55
This is a common issue we've run into before on Mac that we unfortunately don't have a solid solution for yet. However, since you've written such a solid issue I think we can track the process to finding a fix here.

Your suspicions are correct, the issue is due to the face that the dongle is not being detected by your system. Supposedly, that BLED112 dongle [should work out of the box on OSX](http://www.picaxe.com/BLED112-Bluetooth-USB-Dongle/), but we've seen that not be case all the time.

You might have some look going through forum posts like these: https://lists.apple.com/archives/bluetooth-dev/2012/Aug/msg00035.html

**Comment by lguerdan** [comment] 2018-11-04 06:14
Thanks for the feedback, I wasn't sure if I was missing something obvious. I'd be happy to provide more system specs / debugging info if that would be helpful. 

In the meantime I will take a look at that post and similar threads.

**Comment by royyannick** [comment] 2018-12-10 16:59
Hey @lguerdan, is your device simply not recognized or is it "busy"?
The last error message will be "pygatt.exceptions.NotConnectedError: No BGAPI compatible device detected" but if you scroll in the logs, do you get something like _"Resource busy: '/dev/cu.usbmodem1'"_ ?

The issue https://github.com/peplin/pygatt/issues/159 you referred to did solve the problem on my side for a "Busy Device". I can now run muselsl on my Mac OSX as of Dec. 10th with a fresh python36 environment with the eeg-notebooks requirements install.

**Comment by jdpigeon** [comment] 2018-12-12 18:04
Hey @lguerdan, I've just merged a PR that updates the pygatt dependency to hopefully fix these sorts of issues on OSX. Could you give it another try with this new version and see if it helps?

**Comment by jdpigeon** [comment] 2018-12-12 18:12
I've updated muselsl on pip so you can test the new version with `pip install muselsl`

**Comment by lguerdan** [comment] 2018-12-13 01:47
Hey @royyannick thanks for the tip. I am not getting any resources busy messages beyond the "No BGAPI compatible device detected", which may explain why addressing [peplin/pygatt#159 ](peplin/pygatt#159 ) didn't help in my case. 

After running a fresh pip install I am getting a new error, which during handling produces the old one (now running with python 3): 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/bgapi/bgapi.py", line 155, in _open_serial_port
    serial_port = self._serial_port or self._detect_device_port()
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/bgapi/bgapi.py", line 131, in _detect_device_port
    raise BGAPIError("Unable to auto-detect BLED112 serial port")
pygatt.backends.bgapi.exceptions.BGAPIError: Unable to auto-detect BLED112 serial port

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/muselsl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/muselsl/__main__.py", line 51, in main
    cli = CLI(args.command)
  File "/usr/local/lib/python3.7/site-packages/muselsl/cli.py", line 9, in __init__
    getattr(self, command)()
  File "/usr/local/lib/python3.7/site-packages/muselsl/cli.py", line 42, in stream
    args.interface, args.name)
  File "/usr/local/lib/python3.7/site-packages/muselsl/stream.py", line 61, in stream
    found_muse = find_muse(name)
  File "/usr/local/lib/python3.7/site-packages/muselsl/stream.py", line 47, in find_muse
    muses = list_muses()
  File "/usr/local/lib/python3.7/site-packages/muselsl/stream.py", line 25, in list_muses
    adapter.start()
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/bgapi/bgapi.py", line 187, in start
    self._open_serial_port(max_connection_attempts=1)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/bgapi/bgapi.py", line 170, in _open_serial_port
    "No BGAPI compatible device detected")
pygatt.exceptions.NotConnectedError: No BGAPI compatible device detected
```
Not seeing any Muse info in the system profiler makes me think it may be a lower-level problem, may try an OS upgrade as well. 

I haven't had time to look at this deeply but will figure it out next week and let you know what I find out.

**Comment by lguerdan** [comment] 2019-02-03 16:40
@fireant and others, this issue was caused by a defective BLED 112 Dongle not recognized by my machine. After getting a replacement everything is working as expected. Thank you for the help!

**Comment by DSLituiev** [comment] 2019-02-07 06:51
@lguerdan I am having the same issue. How did you diagnose that BLED112 was defective?

**Comment by lguerdan** [comment] 2019-02-08 18:18
I ran `system_profiler SPUSBDataType` in my command line and also checked `Sytem Information -> USB`, but didn't see any Low Energy Dongle appear, so it sounds like your issue may be different. See [this discussion](https://www.silabs.com/community/wireless/bluetooth/forum.topic.html/unable_to_detectble-AYE5) form for my debugging with the Silicon Labs folks.

**Closed** 2019-10-23 00:02 UTC
